// <auto-generated />
using HealthService.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HealthService.Migrations
{
    [DbContext(typeof(HealthDbContext))]
    partial class HealthDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HealthService.Models.PersonalInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BloodType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FitnessLevel")
                        .HasColumnType("int");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<int>("ProfileId")
                        .HasColumnType("int");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PersonalInfo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BloodType = "O+",
                            FitnessLevel = 3,
                            Height = 168,
                            ProfileId = 1,
                            Weight = 72
                        },
                        new
                        {
                            Id = 2,
                            BloodType = "O+",
                            FitnessLevel = 2,
                            Height = 169,
                            ProfileId = 2,
                            Weight = 76
                        },
                        new
                        {
                            Id = 3,
                            BloodType = "A+",
                            FitnessLevel = 1,
                            Height = 170,
                            ProfileId = 3,
                            Weight = 81
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
